/*
 * COPIED FROM GENERATED jOOQ CODE!!!
 *
 * This file is generated by jOOQ.
 */
package util;


import java.io.Serializable;

public class Haustier implements Serializable {

    private static final long serialVersionUID = 1L;

    private String  spitzname;
    private String  besitzer;
    private Integer lieblingsspielzeug;
    private Integer alter;

    public Haustier() {}

    public Haustier(Haustier value) {
        this.spitzname = value.spitzname;
        this.besitzer = value.besitzer;
        this.lieblingsspielzeug = value.lieblingsspielzeug;
        this.alter = value.alter;
    }

    public Haustier(
            String  spitzname,
            String  besitzer,
            Integer lieblingsspielzeug,
            Integer alter
    ) {
        this.spitzname = spitzname;
        this.besitzer = besitzer;
        this.lieblingsspielzeug = lieblingsspielzeug;
        this.alter = alter;
    }

    /**
     * Getter for <code>pmiw22_pets_advanced.haustier.Spitzname</code>.
     */
    public String getSpitzname() {
        return this.spitzname;
    }

    /**
     * Setter for <code>pmiw22_pets_advanced.haustier.Spitzname</code>.
     */
    public void setSpitzname(String spitzname) {
        this.spitzname = spitzname;
    }

    /**
     * Getter for <code>pmiw22_pets_advanced.haustier.Besitzer</code>.
     */
    public String getBesitzer() {
        return this.besitzer;
    }

    /**
     * Setter for <code>pmiw22_pets_advanced.haustier.Besitzer</code>.
     */
    public void setBesitzer(String besitzer) {
        this.besitzer = besitzer;
    }

    /**
     * Getter for <code>pmiw22_pets_advanced.haustier.Lieblingsspielzeug</code>.
     */
    public Integer getLieblingsspielzeug() {
        return this.lieblingsspielzeug;
    }

    /**
     * Setter for <code>pmiw22_pets_advanced.haustier.Lieblingsspielzeug</code>.
     */
    public void setLieblingsspielzeug(Integer lieblingsspielzeug) {
        this.lieblingsspielzeug = lieblingsspielzeug;
    }

    /**
     * Getter for <code>pmiw22_pets_advanced.haustier.Alter</code>.
     */
    public Integer getAlter() {
        return this.alter;
    }

    /**
     * Setter for <code>pmiw22_pets_advanced.haustier.Alter</code>.
     */
    public void setAlter(Integer alter) {
        this.alter = alter;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Haustier other = (Haustier) obj;
        if (spitzname == null) {
            if (other.spitzname != null)
                return false;
        }
        else if (!spitzname.equals(other.spitzname))
            return false;
        if (besitzer == null) {
            if (other.besitzer != null)
                return false;
        }
        else if (!besitzer.equals(other.besitzer))
            return false;
        if (lieblingsspielzeug == null) {
            if (other.lieblingsspielzeug != null)
                return false;
        }
        else if (!lieblingsspielzeug.equals(other.lieblingsspielzeug))
            return false;
        if (alter == null) {
            return other.alter == null;
        }
        else return alter.equals(other.alter);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.spitzname == null) ? 0 : this.spitzname.hashCode());
        result = prime * result + ((this.besitzer == null) ? 0 : this.besitzer.hashCode());
        result = prime * result + ((this.lieblingsspielzeug == null) ? 0 : this.lieblingsspielzeug.hashCode());
        result = prime * result + ((this.alter == null) ? 0 : this.alter.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "Haustier (" + spitzname +
                ", " + besitzer +
                ", " + lieblingsspielzeug +
                ", " + alter +
                ")";
        return sb;
    }
}

